### ISSUE TITLE
Implementing with fish shell

### ISSUE THREAD

**Issue by 0xpetersatoshi** [gibbling/dircolors#1]
Any way you could provide instructions on how to integrate with fish shell?

**Comment by gibbling** [comment]
Put this in your init.fish
```
# Dircolors
# ~/.dircolors/themefile
if test -e ~/.dircolors
    switch (uname)
        case Darwin
            eval (gdircolors -c ~/.dircolors/dircolors.256dark)

        case Linux
            eval (dircolors -c ~/.dircolors/dircolors.256dark)
    end
end
```

**Comment by 0xpetersatoshi** [comment]
I don't think I have an init.fish file. Did you mean config.fish? I tried placing that code in my config.fish file but no change. I then created an init.fish file and placed it in `~/.config/fish/init.fish` and pasted the code and restarted and still no success.

**Comment by 0xpetersatoshi** [comment]
I placed it in my ~/.config/fish/config.fish file and then remembered that I needed to alias `ls` to `gls --color=auto` and it worked perfectly fine! Thank you!
